import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";

const lato = Lato({
  weight: ["400", "700"], // ✅ WAJIB: berat font yang digunakan
  subsets: ["latin"],
  variable: "--font-lato", // opsional kalau mau pakai CSS variable
});

export const metadata: Metadata = {
  title: "Landing Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lato.variable} ${lato.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
